### ISSUE TITLE
Can't see the compiled .JAR file?

### ISSUE THREAD

**Issue by SirClickALot** [Belotti01/CPU-Visual-Simulator#3]
Hi,

I'm keen to take a local look at this but I cannot any sign of the single .jar file you refer to?

Do I need to use Java locally to package it up myself?
If so, then any instructions on doing so would be most welcome.

"This Educational CPU Visual Simulator is implemented in Java, and packaged as a single .jar file that you need to download from here...."

Thanks

Nick

**Comment by Belotti01** [comment]
The .jar release can be found in the _Releases_ section on the left of the _Code_  page of the repository.
Direct link to download the package: https://github.com/Belotti01/CPU-Visual-Simulator/releases/download/v1.0.0/CPU.Visual.Simulator.jar
